using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;

namespace zCRMConsoleApp.Models
{
    public partial class FacilityDID
    {
        [Column("New_FacilityDIDId")]
        
         public Guid FacilityDIDId { get; set; }     
         public int? DeletionStateCode { get; set; }      
         public DateTime? CreatedOn { get; set; }       
         public Guid? CreatedBy { get; set; }        
         public DateTime? ModifiedOn { get; set; }        
         public Guid? ModifiedBy { get; set; }       
         public Guid? OrganizationId { get; set; }        
         public string StateCode { get; set; }        
         public string StatusCode { get; set; }        
         public string DID { get; set; }       
         public string Description { get; set; }       
         public Guid? FacilityId { get; set; }       
         public string FullNumber { get; set; }       
         public Guid? CallSourceId { get; set; }       
         public string TrackingNumber { get; set; }      
         public string TrackingNumberOwner { get; set; }       
         public string CiscoApplication { get; set; }     
         public string CiscoScript { get; set; }      
         public bool? AfterHours { get; set; }        
         public bool? Holiday { get; set; }        
         public string AfterHoursNumber { get; set; }        
         public string VoicemailNumber { get; set; }        
         public string MainQueue { get; set; }        
         public string AdvertisingPrompt { get; set; }        
         public string WelcomePrompt { get; set; }        
         public string AllAgentBusyPrompt { get; set; }        
         public string SecondaryQueueTrigger { get; set; }       
         public string SecondaryQueue { get; set; }       
         public string IVRoption1Queue { get; set; }        
         public string IVRoption2Queue { get; set; }       
         public string IVRoption3TransferNumber { get; set; }       
         public bool? CustomSKS { get; set; }       
         public bool? CustomDahn { get; set; }      
         public string MondayStartTime { get; set; }       
         public bool? UseIVR { get; set; }       
         public string MondayEndTime { get; set; }       
         public string TuesdayStartTime { get; set; }       
         public string TuesdayEndTime { get; set; }       
         public string WednesdayStartTime { get; set; }      
         public string WednesdayEndTime { get; set; }    
         public string ThursdayStartTime { get; set; }        
         public string ThursdayEndTime { get; set; }       
         public string FridayStartTime { get; set; }        
         public string FridayEndTime { get; set; }        
         public string SaturdayStartTime { get; set; }       
         public string SaturdayEndTime { get; set; }      
         public string SundayStartTime { get; set; }
         public string SundayEndTime { get; set; }
         public int? FacilityTransferTimeout { get; set; }
         public string FacilityTransferNumber { get; set; }
         public string FallbackQueue { get; set; }
         public string AreaCode { get; set; }
         public string Prefix { get; set; }
         public string LastFour { get; set; }
         public string OutsidePaymentPrompt { get; set; }
         public string OutsidePaymentNumber { get; set; }
         public string NightVoicemail { get; set; }
         public bool? CustomStorQuest { get; set; }
         public string OutsidePaymentPromptAfterHours { get; set; }
         public string DayVoicemailGreeting { get; set; }
         public string NightVoicemailGreeting { get; set; }
         public string CallerIdExemptNumbers { get; set; }
         public string ExtraAgentQueue { get; set; }
         public bool? EnableSpanish { get; set; }
         public string SpanishWelcomePrompt { get; set; }
         public string SpanishQueue { get; set; }
         public string SpanishIVROption1Queue { get; set; }
         public string SpanishIVROption2Queue { get; set; }
         public bool? UseAfterhoursScript { get; set; }
         public string AccessHold1 { get; set; }
         public string AccessHold2 { get; set; }
         public string AccessHold3 { get; set; }
         public string AccessHold4 { get; set; }
         public bool? CustomAccess { get; set; }
         public string AccessVoicemail { get; set; }
         public string AccessQueue { get; set; }
         public int? AccessCallCenter { get; set; }
         public string AccessGreeting { get; set; }
         public bool? AdminDID { get; set; }
         public string AccessBackDoorNumber { get; set; }
         public bool? UsePayByPhone { get; set; }
         public string PaybyPhoneOptionNumber { get; set; }
         public string PaybyPhoneFallbackQueue { get; set; }
         public string PaybyPhoneFallbackType { get; set; }
         public string PaybyPhoneFallbackPhoneNumber { get; set; }
         public string XpressPayAfterHoursPrompt { get; set; }
         public bool? XpressPayOnly { get; set; }
         public bool? FailedTest { get; set; }
         public bool? ConflictedDID { get; set; }
         public string AskforSpanishGreeting { get; set; }
         public bool? EnableLiveManager { get; set; }
         public int? LiveManagerOption { get; set; }
         public string LiveManagerExtension { get; set; }
         public bool? LiveManagerOnly { get; set; }
         public bool? UseSpecialSalesQueue { get; set; }
         public string DahnBackDoorNumber { get; set; }
         public bool? DahnUseIVR { get; set; }
         public string TenDigitDID { get; set; }
         public int? Store40InquirySourceId { get; set; }
         public bool? UseXpressRes { get; set; }
         public string XpressResSecondMenuPrompt { get; set; }
         public bool? CustomHideAway { get; set; }
         public string ConvenienceFeeIvrprompt { get; set; }
         public bool? SkipIVR { get; set; }
         public Guid? DefaultCallTypeId { get; set; }
         public Guid? DefaultCallResultId { get; set; }
         public bool? CustomB2I { get; set; }
         public string UrlToLaunch { get; set; }
         public bool? CustomMetro { get; set; }
         public string SpanishPrompt { get; set; }
         public string SecondMenuPrompt { get; set; }
         public string StoreHoursPrompt { get; set; }
         public bool? CustomPlatinum { get; set; }
         public bool? TwentyFourHours { get; set; }
         public bool? CustomRedDot { get; set; }
         public string RedDotWelcomePrompt { get; set; }
         public bool? StoreQuestUseOption1SubMenu { get; set; }
         public string StoreQuestOption1SubMenuPrompt { get; set; }
         public bool? CustomRealStorage { get; set; }
         public bool? CustomPhoneSmart { get; set; }
         public string PreWelcomePrompt { get; set; }
         public bool? EnableOption3 { get; set; }
         public string PhoneSmartOption3TransferNumber { get; set; }
         public bool? EnableFacilityVoicemailFallback { get; set; }
         public bool? IsStorageTreasuresVip { get; set; }
         public bool? USStorageSearchUse { get; set; }
         public bool? CustomSimply { get; set; }
         public string SpanishConvenienceFeePrompt { get; set; }
         public string CreatedByName { get; set; }
         public string ModifiedByName { get; set; }
         public string FacilityName { get; set; }
    }
}
